#include "../../mlai/mlai.cpp"
#include "../../../../libs/image/image.cpp"
#include "../../../../libs/mnist/mnist.cpp"
#include "../../../../libs/alloc_type/alloc_type.cpp"
#include "../../../../libs/span/span.cpp"
#include "../../../../libs/qsprintf/qsprintf.cpp"